#配置服务的端口号
server:
  port: 14000
# 配置session的失效时间
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-auth-server
  profiles:
    active: dev
#  开发过程中关闭thymeleaf缓存
  thymeleaf:
    cache: false
# 指定springsession的存储类型
  session:
    store-type: redis


#配置日志级别，进行显示sql日志
logging:
  level:
    com.yama.mall: debug
    
#验证码的有效时间
verityCode:
  validTime:
    minute: 3