spring:
  application:
    name: gulimall-search
  profiles:
    active: dev
  # 使用jackson.data-format配置所有时间数据转换json都会转换成配置的格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#配置服务的端口号
server:
  port: 13000


#配置日志级别，进行显示sql日志
logging:
  level:
    com.yama.mall: debug

#防止远程调用方法读取超时，连接超时,因为第一次连接redis时，会时间比较长，放置读取失败
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
