#配置服务的端口号
server:
  port: 88

spring:
  application:
    name: gulimall-gateway
  profiles:
    active: dev
  #通过网关进行指定访问
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: third-party-route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}
        - id: member-route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: ware-route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: search-route
          uri: lb://gulimall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: admin-route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
#        根据域名转发服务，配置过nginx后，网关接收到转的请求再次转给指定服务
#        gulimall.com是网站的首页域名
        - id: gulimall-product_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com
#        search.gulimall.com域名是为网站的搜索页的指定域名
        - id: gulimall-search
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com
        

  
