#配置服务的端口号
server:
  port: 15000

spring:
  application:
    name: gulimall-cart
  profiles:
    active: dev
#  开发过程中关闭thymeleaf缓存
  thymeleaf:
    cache: false



#配置日志级别，进行显示sql日志
logging:
  level:
    com.yama.mall: debug
    