#配置服务的端口号
server:
  port: 15000

spring:
  application:
    name: gulimall-cart
  profiles:
    active: dev
#  开发过程中关闭thymeleaf缓存
  thymeleaf:
    cache: false
# 配置spring session的存储类型
  session:
    store-type: redis

#配置日志级别，进行显示sql日志
logging:
  level:
    com.yama.mall: debug
    
#线程池属性配置参数
gulimall:
  thread:
    coreSize: 2
    maxSize: 4
    keepAliveTime: 30
    